%%% Test the simulation of Hawkes process

% Supress warnings on missing semicolon
%#ok<*NOPTS>

clc; clear all; close all;  % clear console


%% Parameter Setting

T_stop = 10;   % terminal Time T

D      = 1;      % dimension of multivariate hawkes

% background intensity [Dx1]
mu       = 0.75 * ones(D, 1);  
         
% intensity from edge effect [DxD]
Y0       = 1.2 * ones(D);

% rate of decay [DxD]
delta    = 1.0 * ones(D);

% parameters for Y [DxDxNy] : Ny = num parameters for each Y
% assumes Gamma(shape,rate)
distY = 'gamma';

shape = 5000;
rate  = 10000;

parY(:,:,1) = shape * ones(D,D,1);
parY(:,:,2) = 1/rate * ones(D,D,1);


% parameters for X [Dx(D+1)xNx] : Nx = num parameters for each X (marked)
% 1st column correspond to marked generated by immigrant
% assumes Normal X
distX = 'normal';

meanX   = 0.0;
stddevX = 1.0;

parX(:,:,1) = meanX   * ones(D,D+1,1);
parX(:,:,2) = stddevX * ones(D,D+1,1);






%% Simulate Hawkes

[t, Y, X, Z] = SimulateMarkedHawkes(T_stop, mu, Y0, delta, distY, parY, distX, parX);



% [t, Y, X, Z] = SimulateMarkedHawkes(T_stop, mu, Y0, delta, distY, parY);

